<?php
return array (
  'ZC_DATABASE_TYPE' => 'mysqli',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => '120.26.219.206',
  'ZC_MYSQL_USERNAME' => '120_26_219_206_1',
  'ZC_MYSQL_PASSWORD' => 'tMGEW7jZewdzJSWb',
  'ZC_MYSQL_NAME' => 'test_first',
  'ZC_MYSQL_CHARSET' => 'utf8mb4',
  'ZC_MYSQL_COLLATE' => 'utf8mb4_general_ci',
  'ZC_MYSQL_PRE' => 'zbp_',
  'ZC_MYSQL_ENGINE' => 'MyISAM',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_PGSQL_SERVER' => '120.26.219.206',
  'ZC_PGSQL_USERNAME' => 'postgres',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => 'utf8',
  'ZC_PGSQL_PRE' => 'zbp_',
  'ZC_PGSQL_PORT' => '5432',
  'ZC_PGSQL_PERSISTENT' => false,
);